# The below is pulled from upstream and slightly modified
# https://github.com/webiny/action-conventional-commits/blob/master/README.md#usage

name: Conventional Commits

on:
  pull_request:

jobs:
  build:
    name: Conventional Commits
    # TODO: switch back to ubuntu-latest
    runs-on: [self-hosted, x64, private-repos]
    steps:
      - uses: actions/checkout@v4

      - uses: webiny/action-conventional-commits@v1.2.0
